=begin
#API2Cart OpenAPI

#API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module OpenapiClient
  class CartCreate
    # Store’s identifier which you can get from cart_list method
    attr_accessor :cart_id

    # A web address of a store that you would like to connect to API2Cart
    attr_accessor :store_url

    # This parameter allows to set up store with custom bridge url (also you must use store_root parameter if a bridge folder is not in the root folder of the store)
    attr_accessor :bridge_url

    # Absolute path to the store root directory (used with \"bridge_url\" parameter)
    attr_accessor :store_root

    # Set this parameter if bridge is already uploaded to store
    attr_accessor :store_key

    # Shared secret
    attr_accessor :shared_secret

    # Specify if api2cart should validate cart version
    attr_accessor :validate_version

    # Enables or disables cart's verification
    attr_accessor :verify

    # DB tables prefix
    attr_accessor :db_tables_prefix

    # This parameter allows you to set your custom user agent, which will be used in requests to the store. Please use it cautiously, as the store's firewall may block specific values.
    attr_accessor :user_agent

    # FTP connection host
    attr_accessor :ftp_host

    # FTP User
    attr_accessor :ftp_user

    # FTP Password
    attr_accessor :ftp_password

    # FTP Port
    attr_accessor :ftp_port

    # FTP Store dir
    attr_accessor :ftp_store_dir

    # 3DCart API Key
    attr_accessor :api_key_3dcart

    # It's a BigCommerce account for which API is enabled
    attr_accessor :admin_account

    # BigCommerce API URL
    attr_accessor :api_path

    # Bigcommerce API Key
    attr_accessor :api_key_bigcommerce

    # Client ID of the requesting app
    attr_accessor :client_id

    # Access token authorizing the app to access resources on behalf of a user
    attr_accessor :access_token

    # API Path section unique to the store
    attr_accessor :context

    # Access token authorizing the app to access resources on behalf of a user
    attr_accessor :access_token

    # Shopify API Key
    attr_accessor :api_key_shopify

    # Shopify API Password
    attr_accessor :api_password

    # Access token authorizing the app to access resources on behalf of a user
    attr_accessor :access_token_shopify

    # Neto API Key
    attr_accessor :api_key

    # Neto User Name
    attr_accessor :api_username

    # Volusion API Password
    attr_accessor :encrypted_password

    # It's a Volusion account for which API is enabled
    attr_accessor :login

    # It's a AspDotNetStorefront account for which API is available
    attr_accessor :api_user_adnsf

    # AspDotNetStorefront API Password
    attr_accessor :api_pass

    # 3DCart Application Private Key
    attr_accessor :private_key

    # 3DCart Token from Application
    attr_accessor :app_token

    # Etsy keystring
    attr_accessor :etsy_keystring

    # Etsy shared secret
    attr_accessor :etsy_shared_secret

    # Secret token authorizing the app to access resources on behalf of a user
    attr_accessor :token_secret

    # Etsy Client Id
    attr_accessor :etsy_client_id

    # Etsy Refresh token
    attr_accessor :etsy_refresh_token

    # Application ID (AppID).
    attr_accessor :ebay_client_id

    # Shared Secret from eBay application
    attr_accessor :ebay_client_secret

    # The RuName value that eBay assigns to your application.
    attr_accessor :ebay_runame

    # Used to authenticate API requests.
    attr_accessor :ebay_access_token

    # Used to renew the access token.
    attr_accessor :ebay_refresh_token

    # eBay environment
    attr_accessor :ebay_environment

    # eBay global ID
    attr_accessor :ebay_site_id

    # Demandware client id
    attr_accessor :dw_client_id

    # Demandware api password
    attr_accessor :dw_api_pass

    # Demandware user name
    attr_accessor :demandware_user_name

    # Demandware user password
    attr_accessor :demandware_user_password

    # Store Id
    attr_accessor :store_id

    # Seller Id
    attr_accessor :seller_id

    # 
    attr_accessor :environment

    # Omni Commerce Connector Client ID
    attr_accessor :hybris_client_id

    # Omni Commerce Connector Client Secret
    attr_accessor :hybris_client_secret

    # User Name
    attr_accessor :hybris_username

    # User password
    attr_accessor :hybris_password

    # Websites to stores mapping data
    attr_accessor :hybris_websites

    # Walmart client ID. For the region 'ca' use Consumer ID
    attr_accessor :walmart_client_id

    # Walmart client secret. For the region 'ca' use Private Key
    attr_accessor :walmart_client_secret

    # Walmart environment
    attr_accessor :walmart_environment

    # Walmart WM_CONSUMER.CHANNEL.TYPE header
    attr_accessor :walmart_channel_type

    # Walmart region
    attr_accessor :walmart_region

    # LightSpeed api key
    attr_accessor :lightspeed_api_key

    # LightSpeed api secret
    attr_accessor :lightspeed_api_secret

    # Access token authorizing the app to access resources on behalf of a user
    attr_accessor :shoplazza_access_token

    # Shared secret
    attr_accessor :shoplazza_shared_secret

    # Shopware access key
    attr_accessor :shopware_access_key

    # Shopware api key
    attr_accessor :shopware_api_key

    # Shopware client secret access key
    attr_accessor :shopware_api_secret

    # CommerceHQ api key
    attr_accessor :commercehq_api_key

    # CommerceHQ api password
    attr_accessor :commercehq_api_password

    # 3DCart Private Key
    attr_accessor :_3dcart_private_key

    # 3DCart Token
    attr_accessor :_3dcart_access_token

    # Woocommerce consumer key
    attr_accessor :wc_consumer_key

    # Woocommerce consumer secret
    attr_accessor :wc_consumer_secret

    # Magento Consumer Key
    attr_accessor :magento_consumer_key

    # Magento Consumer Secret
    attr_accessor :magento_consumer_secret

    # Magento Access Token
    attr_accessor :magento_access_token

    # Magento Token Secret
    attr_accessor :magento_token_secret

    # Prestashop webservice key
    attr_accessor :prestashop_webservice_key

    # Wix App ID
    attr_accessor :wix_app_id

    # Wix App Secret Key
    attr_accessor :wix_app_secret_key

    # Wix Instance ID
    attr_accessor :wix_instance_id

    # Wix refresh token
    attr_accessor :wix_refresh_token

    # Mercado Libre App ID
    attr_accessor :mercado_libre_app_id

    # Mercado Libre App Secret Key
    attr_accessor :mercado_libre_app_secret_key

    # Mercado Libre Refresh Token
    attr_accessor :mercado_libre_refresh_token

    # Zid Client ID
    attr_accessor :zid_client_id

    # Zid Client Secret
    attr_accessor :zid_client_secret

    # Zid Access Token
    attr_accessor :zid_access_token

    # Zid Authorization
    attr_accessor :zid_authorization

    # Zid refresh token
    attr_accessor :zid_refresh_token

    # Flipkart Client ID
    attr_accessor :flipkart_client_id

    # Flipkart Client Secret
    attr_accessor :flipkart_client_secret

    # Allegro Client ID
    attr_accessor :allegro_client_id

    # Allegro Client Secret
    attr_accessor :allegro_client_secret

    # Allegro Access Token
    attr_accessor :allegro_access_token

    # Allegro Refresh Token
    attr_accessor :allegro_refresh_token

    # Allegro Environment
    attr_accessor :allegro_environment

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cart_id' => :'cart_id',
        :'store_url' => :'store_url',
        :'bridge_url' => :'bridge_url',
        :'store_root' => :'store_root',
        :'store_key' => :'store_key',
        :'shared_secret' => :'shared_secret',
        :'validate_version' => :'validate_version',
        :'verify' => :'verify',
        :'db_tables_prefix' => :'db_tables_prefix',
        :'user_agent' => :'user_agent',
        :'ftp_host' => :'ftp_host',
        :'ftp_user' => :'ftp_user',
        :'ftp_password' => :'ftp_password',
        :'ftp_port' => :'ftp_port',
        :'ftp_store_dir' => :'ftp_store_dir',
        :'api_key_3dcart' => :'apiKey_3dcart',
        :'admin_account' => :'AdminAccount',
        :'api_path' => :'ApiPath',
        :'api_key_bigcommerce' => :'ApiKey_Bigcommerce',
        :'client_id' => :'client_id',
        :'access_token' => :'accessToken',
        :'context' => :'context',
        :'access_token' => :'access_token',
        :'api_key_shopify' => :'apiKey_shopify',
        :'api_password' => :'apiPassword',
        :'access_token_shopify' => :'accessToken_shopify',
        :'api_key' => :'apiKey',
        :'api_username' => :'apiUsername',
        :'encrypted_password' => :'EncryptedPassword',
        :'login' => :'Login',
        :'api_user_adnsf' => :'apiUser_adnsf',
        :'api_pass' => :'apiPass',
        :'private_key' => :'privateKey',
        :'app_token' => :'appToken',
        :'etsy_keystring' => :'etsy_keystring',
        :'etsy_shared_secret' => :'etsy_shared_secret',
        :'token_secret' => :'tokenSecret',
        :'etsy_client_id' => :'etsy_client_id',
        :'etsy_refresh_token' => :'etsy_refresh_token',
        :'ebay_client_id' => :'ebay_client_id',
        :'ebay_client_secret' => :'ebay_client_secret',
        :'ebay_runame' => :'ebay_runame',
        :'ebay_access_token' => :'ebay_access_token',
        :'ebay_refresh_token' => :'ebay_refresh_token',
        :'ebay_environment' => :'ebay_environment',
        :'ebay_site_id' => :'ebay_site_id',
        :'dw_client_id' => :'dw_client_id',
        :'dw_api_pass' => :'dw_api_pass',
        :'demandware_user_name' => :'demandware_user_name',
        :'demandware_user_password' => :'demandware_user_password',
        :'store_id' => :'store_id',
        :'seller_id' => :'seller_id',
        :'environment' => :'environment',
        :'hybris_client_id' => :'hybris_client_id',
        :'hybris_client_secret' => :'hybris_client_secret',
        :'hybris_username' => :'hybris_username',
        :'hybris_password' => :'hybris_password',
        :'hybris_websites' => :'hybris_websites',
        :'walmart_client_id' => :'walmart_client_id',
        :'walmart_client_secret' => :'walmart_client_secret',
        :'walmart_environment' => :'walmart_environment',
        :'walmart_channel_type' => :'walmart_channel_type',
        :'walmart_region' => :'walmart_region',
        :'lightspeed_api_key' => :'lightspeed_api_key',
        :'lightspeed_api_secret' => :'lightspeed_api_secret',
        :'shoplazza_access_token' => :'shoplazza_access_token',
        :'shoplazza_shared_secret' => :'shoplazza_shared_secret',
        :'shopware_access_key' => :'shopware_access_key',
        :'shopware_api_key' => :'shopware_api_key',
        :'shopware_api_secret' => :'shopware_api_secret',
        :'commercehq_api_key' => :'commercehq_api_key',
        :'commercehq_api_password' => :'commercehq_api_password',
        :'_3dcart_private_key' => :'3dcart_private_key',
        :'_3dcart_access_token' => :'3dcart_access_token',
        :'wc_consumer_key' => :'wc_consumer_key',
        :'wc_consumer_secret' => :'wc_consumer_secret',
        :'magento_consumer_key' => :'magento_consumer_key',
        :'magento_consumer_secret' => :'magento_consumer_secret',
        :'magento_access_token' => :'magento_access_token',
        :'magento_token_secret' => :'magento_token_secret',
        :'prestashop_webservice_key' => :'prestashop_webservice_key',
        :'wix_app_id' => :'wix_app_id',
        :'wix_app_secret_key' => :'wix_app_secret_key',
        :'wix_instance_id' => :'wix_instance_id',
        :'wix_refresh_token' => :'wix_refresh_token',
        :'mercado_libre_app_id' => :'mercado_libre_app_id',
        :'mercado_libre_app_secret_key' => :'mercado_libre_app_secret_key',
        :'mercado_libre_refresh_token' => :'mercado_libre_refresh_token',
        :'zid_client_id' => :'zid_client_id',
        :'zid_client_secret' => :'zid_client_secret',
        :'zid_access_token' => :'zid_access_token',
        :'zid_authorization' => :'zid_authorization',
        :'zid_refresh_token' => :'zid_refresh_token',
        :'flipkart_client_id' => :'flipkart_client_id',
        :'flipkart_client_secret' => :'flipkart_client_secret',
        :'allegro_client_id' => :'allegro_client_id',
        :'allegro_client_secret' => :'allegro_client_secret',
        :'allegro_access_token' => :'allegro_access_token',
        :'allegro_refresh_token' => :'allegro_refresh_token',
        :'allegro_environment' => :'allegro_environment'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cart_id' => :'String',
        :'store_url' => :'String',
        :'bridge_url' => :'String',
        :'store_root' => :'String',
        :'store_key' => :'String',
        :'shared_secret' => :'String',
        :'validate_version' => :'Boolean',
        :'verify' => :'Boolean',
        :'db_tables_prefix' => :'String',
        :'user_agent' => :'String',
        :'ftp_host' => :'String',
        :'ftp_user' => :'String',
        :'ftp_password' => :'String',
        :'ftp_port' => :'Integer',
        :'ftp_store_dir' => :'String',
        :'api_key_3dcart' => :'String',
        :'admin_account' => :'String',
        :'api_path' => :'String',
        :'api_key_bigcommerce' => :'String',
        :'client_id' => :'String',
        :'access_token' => :'String',
        :'context' => :'String',
        :'access_token' => :'String',
        :'api_key_shopify' => :'String',
        :'api_password' => :'String',
        :'access_token_shopify' => :'String',
        :'api_key' => :'String',
        :'api_username' => :'String',
        :'encrypted_password' => :'String',
        :'login' => :'String',
        :'api_user_adnsf' => :'String',
        :'api_pass' => :'String',
        :'private_key' => :'String',
        :'app_token' => :'String',
        :'etsy_keystring' => :'String',
        :'etsy_shared_secret' => :'String',
        :'token_secret' => :'String',
        :'etsy_client_id' => :'String',
        :'etsy_refresh_token' => :'String',
        :'ebay_client_id' => :'String',
        :'ebay_client_secret' => :'String',
        :'ebay_runame' => :'String',
        :'ebay_access_token' => :'String',
        :'ebay_refresh_token' => :'String',
        :'ebay_environment' => :'String',
        :'ebay_site_id' => :'Integer',
        :'dw_client_id' => :'String',
        :'dw_api_pass' => :'String',
        :'demandware_user_name' => :'String',
        :'demandware_user_password' => :'String',
        :'store_id' => :'String',
        :'seller_id' => :'String',
        :'environment' => :'String',
        :'hybris_client_id' => :'String',
        :'hybris_client_secret' => :'String',
        :'hybris_username' => :'String',
        :'hybris_password' => :'String',
        :'hybris_websites' => :'Array<AccountCartAddHybrisWebsitesInner>',
        :'walmart_client_id' => :'String',
        :'walmart_client_secret' => :'String',
        :'walmart_environment' => :'String',
        :'walmart_channel_type' => :'String',
        :'walmart_region' => :'String',
        :'lightspeed_api_key' => :'String',
        :'lightspeed_api_secret' => :'String',
        :'shoplazza_access_token' => :'String',
        :'shoplazza_shared_secret' => :'String',
        :'shopware_access_key' => :'String',
        :'shopware_api_key' => :'String',
        :'shopware_api_secret' => :'String',
        :'commercehq_api_key' => :'String',
        :'commercehq_api_password' => :'String',
        :'_3dcart_private_key' => :'String',
        :'_3dcart_access_token' => :'String',
        :'wc_consumer_key' => :'String',
        :'wc_consumer_secret' => :'String',
        :'magento_consumer_key' => :'String',
        :'magento_consumer_secret' => :'String',
        :'magento_access_token' => :'String',
        :'magento_token_secret' => :'String',
        :'prestashop_webservice_key' => :'String',
        :'wix_app_id' => :'String',
        :'wix_app_secret_key' => :'String',
        :'wix_instance_id' => :'String',
        :'wix_refresh_token' => :'String',
        :'mercado_libre_app_id' => :'String',
        :'mercado_libre_app_secret_key' => :'String',
        :'mercado_libre_refresh_token' => :'String',
        :'zid_client_id' => :'Integer',
        :'zid_client_secret' => :'String',
        :'zid_access_token' => :'String',
        :'zid_authorization' => :'String',
        :'zid_refresh_token' => :'String',
        :'flipkart_client_id' => :'String',
        :'flipkart_client_secret' => :'String',
        :'allegro_client_id' => :'String',
        :'allegro_client_secret' => :'String',
        :'allegro_access_token' => :'String',
        :'allegro_refresh_token' => :'String',
        :'allegro_environment' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::CartCreate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::CartCreate`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cart_id')
        self.cart_id = attributes[:'cart_id']
      else
        self.cart_id = nil
      end

      if attributes.key?(:'store_url')
        self.store_url = attributes[:'store_url']
      end

      if attributes.key?(:'bridge_url')
        self.bridge_url = attributes[:'bridge_url']
      end

      if attributes.key?(:'store_root')
        self.store_root = attributes[:'store_root']
      end

      if attributes.key?(:'store_key')
        self.store_key = attributes[:'store_key']
      end

      if attributes.key?(:'shared_secret')
        self.shared_secret = attributes[:'shared_secret']
      end

      if attributes.key?(:'validate_version')
        self.validate_version = attributes[:'validate_version']
      else
        self.validate_version = false
      end

      if attributes.key?(:'verify')
        self.verify = attributes[:'verify']
      else
        self.verify = true
      end

      if attributes.key?(:'db_tables_prefix')
        self.db_tables_prefix = attributes[:'db_tables_prefix']
      end

      if attributes.key?(:'user_agent')
        self.user_agent = attributes[:'user_agent']
      end

      if attributes.key?(:'ftp_host')
        self.ftp_host = attributes[:'ftp_host']
      end

      if attributes.key?(:'ftp_user')
        self.ftp_user = attributes[:'ftp_user']
      end

      if attributes.key?(:'ftp_password')
        self.ftp_password = attributes[:'ftp_password']
      end

      if attributes.key?(:'ftp_port')
        self.ftp_port = attributes[:'ftp_port']
      end

      if attributes.key?(:'ftp_store_dir')
        self.ftp_store_dir = attributes[:'ftp_store_dir']
      end

      if attributes.key?(:'api_key_3dcart')
        self.api_key_3dcart = attributes[:'api_key_3dcart']
      end

      if attributes.key?(:'admin_account')
        self.admin_account = attributes[:'admin_account']
      end

      if attributes.key?(:'api_path')
        self.api_path = attributes[:'api_path']
      end

      if attributes.key?(:'api_key_bigcommerce')
        self.api_key_bigcommerce = attributes[:'api_key_bigcommerce']
      end

      if attributes.key?(:'client_id')
        self.client_id = attributes[:'client_id']
      end

      if attributes.key?(:'access_token')
        self.access_token = attributes[:'access_token']
      end

      if attributes.key?(:'context')
        self.context = attributes[:'context']
      end

      if attributes.key?(:'access_token')
        self.access_token = attributes[:'access_token']
      end

      if attributes.key?(:'api_key_shopify')
        self.api_key_shopify = attributes[:'api_key_shopify']
      end

      if attributes.key?(:'api_password')
        self.api_password = attributes[:'api_password']
      end

      if attributes.key?(:'access_token_shopify')
        self.access_token_shopify = attributes[:'access_token_shopify']
      end

      if attributes.key?(:'api_key')
        self.api_key = attributes[:'api_key']
      end

      if attributes.key?(:'api_username')
        self.api_username = attributes[:'api_username']
      end

      if attributes.key?(:'encrypted_password')
        self.encrypted_password = attributes[:'encrypted_password']
      end

      if attributes.key?(:'login')
        self.login = attributes[:'login']
      end

      if attributes.key?(:'api_user_adnsf')
        self.api_user_adnsf = attributes[:'api_user_adnsf']
      end

      if attributes.key?(:'api_pass')
        self.api_pass = attributes[:'api_pass']
      end

      if attributes.key?(:'private_key')
        self.private_key = attributes[:'private_key']
      end

      if attributes.key?(:'app_token')
        self.app_token = attributes[:'app_token']
      end

      if attributes.key?(:'etsy_keystring')
        self.etsy_keystring = attributes[:'etsy_keystring']
      end

      if attributes.key?(:'etsy_shared_secret')
        self.etsy_shared_secret = attributes[:'etsy_shared_secret']
      end

      if attributes.key?(:'token_secret')
        self.token_secret = attributes[:'token_secret']
      end

      if attributes.key?(:'etsy_client_id')
        self.etsy_client_id = attributes[:'etsy_client_id']
      end

      if attributes.key?(:'etsy_refresh_token')
        self.etsy_refresh_token = attributes[:'etsy_refresh_token']
      end

      if attributes.key?(:'ebay_client_id')
        self.ebay_client_id = attributes[:'ebay_client_id']
      end

      if attributes.key?(:'ebay_client_secret')
        self.ebay_client_secret = attributes[:'ebay_client_secret']
      end

      if attributes.key?(:'ebay_runame')
        self.ebay_runame = attributes[:'ebay_runame']
      end

      if attributes.key?(:'ebay_access_token')
        self.ebay_access_token = attributes[:'ebay_access_token']
      end

      if attributes.key?(:'ebay_refresh_token')
        self.ebay_refresh_token = attributes[:'ebay_refresh_token']
      end

      if attributes.key?(:'ebay_environment')
        self.ebay_environment = attributes[:'ebay_environment']
      else
        self.ebay_environment = 'production'
      end

      if attributes.key?(:'ebay_site_id')
        self.ebay_site_id = attributes[:'ebay_site_id']
      else
        self.ebay_site_id = 0
      end

      if attributes.key?(:'dw_client_id')
        self.dw_client_id = attributes[:'dw_client_id']
      end

      if attributes.key?(:'dw_api_pass')
        self.dw_api_pass = attributes[:'dw_api_pass']
      end

      if attributes.key?(:'demandware_user_name')
        self.demandware_user_name = attributes[:'demandware_user_name']
      end

      if attributes.key?(:'demandware_user_password')
        self.demandware_user_password = attributes[:'demandware_user_password']
      end

      if attributes.key?(:'store_id')
        self.store_id = attributes[:'store_id']
      else
        self.store_id = nil
      end

      if attributes.key?(:'seller_id')
        self.seller_id = attributes[:'seller_id']
      end

      if attributes.key?(:'environment')
        self.environment = attributes[:'environment']
      else
        self.environment = 'production'
      end

      if attributes.key?(:'hybris_client_id')
        self.hybris_client_id = attributes[:'hybris_client_id']
      end

      if attributes.key?(:'hybris_client_secret')
        self.hybris_client_secret = attributes[:'hybris_client_secret']
      end

      if attributes.key?(:'hybris_username')
        self.hybris_username = attributes[:'hybris_username']
      end

      if attributes.key?(:'hybris_password')
        self.hybris_password = attributes[:'hybris_password']
      end

      if attributes.key?(:'hybris_websites')
        if (value = attributes[:'hybris_websites']).is_a?(Array)
          self.hybris_websites = value
        end
      end

      if attributes.key?(:'walmart_client_id')
        self.walmart_client_id = attributes[:'walmart_client_id']
      end

      if attributes.key?(:'walmart_client_secret')
        self.walmart_client_secret = attributes[:'walmart_client_secret']
      end

      if attributes.key?(:'walmart_environment')
        self.walmart_environment = attributes[:'walmart_environment']
      else
        self.walmart_environment = 'production'
      end

      if attributes.key?(:'walmart_channel_type')
        self.walmart_channel_type = attributes[:'walmart_channel_type']
      end

      if attributes.key?(:'walmart_region')
        self.walmart_region = attributes[:'walmart_region']
      else
        self.walmart_region = 'us'
      end

      if attributes.key?(:'lightspeed_api_key')
        self.lightspeed_api_key = attributes[:'lightspeed_api_key']
      end

      if attributes.key?(:'lightspeed_api_secret')
        self.lightspeed_api_secret = attributes[:'lightspeed_api_secret']
      end

      if attributes.key?(:'shoplazza_access_token')
        self.shoplazza_access_token = attributes[:'shoplazza_access_token']
      end

      if attributes.key?(:'shoplazza_shared_secret')
        self.shoplazza_shared_secret = attributes[:'shoplazza_shared_secret']
      end

      if attributes.key?(:'shopware_access_key')
        self.shopware_access_key = attributes[:'shopware_access_key']
      end

      if attributes.key?(:'shopware_api_key')
        self.shopware_api_key = attributes[:'shopware_api_key']
      end

      if attributes.key?(:'shopware_api_secret')
        self.shopware_api_secret = attributes[:'shopware_api_secret']
      end

      if attributes.key?(:'commercehq_api_key')
        self.commercehq_api_key = attributes[:'commercehq_api_key']
      end

      if attributes.key?(:'commercehq_api_password')
        self.commercehq_api_password = attributes[:'commercehq_api_password']
      end

      if attributes.key?(:'_3dcart_private_key')
        self._3dcart_private_key = attributes[:'_3dcart_private_key']
      end

      if attributes.key?(:'_3dcart_access_token')
        self._3dcart_access_token = attributes[:'_3dcart_access_token']
      end

      if attributes.key?(:'wc_consumer_key')
        self.wc_consumer_key = attributes[:'wc_consumer_key']
      end

      if attributes.key?(:'wc_consumer_secret')
        self.wc_consumer_secret = attributes[:'wc_consumer_secret']
      end

      if attributes.key?(:'magento_consumer_key')
        self.magento_consumer_key = attributes[:'magento_consumer_key']
      end

      if attributes.key?(:'magento_consumer_secret')
        self.magento_consumer_secret = attributes[:'magento_consumer_secret']
      end

      if attributes.key?(:'magento_access_token')
        self.magento_access_token = attributes[:'magento_access_token']
      end

      if attributes.key?(:'magento_token_secret')
        self.magento_token_secret = attributes[:'magento_token_secret']
      end

      if attributes.key?(:'prestashop_webservice_key')
        self.prestashop_webservice_key = attributes[:'prestashop_webservice_key']
      end

      if attributes.key?(:'wix_app_id')
        self.wix_app_id = attributes[:'wix_app_id']
      else
        self.wix_app_id = nil
      end

      if attributes.key?(:'wix_app_secret_key')
        self.wix_app_secret_key = attributes[:'wix_app_secret_key']
      else
        self.wix_app_secret_key = nil
      end

      if attributes.key?(:'wix_instance_id')
        self.wix_instance_id = attributes[:'wix_instance_id']
      end

      if attributes.key?(:'wix_refresh_token')
        self.wix_refresh_token = attributes[:'wix_refresh_token']
      end

      if attributes.key?(:'mercado_libre_app_id')
        self.mercado_libre_app_id = attributes[:'mercado_libre_app_id']
      end

      if attributes.key?(:'mercado_libre_app_secret_key')
        self.mercado_libre_app_secret_key = attributes[:'mercado_libre_app_secret_key']
      end

      if attributes.key?(:'mercado_libre_refresh_token')
        self.mercado_libre_refresh_token = attributes[:'mercado_libre_refresh_token']
      end

      if attributes.key?(:'zid_client_id')
        self.zid_client_id = attributes[:'zid_client_id']
      end

      if attributes.key?(:'zid_client_secret')
        self.zid_client_secret = attributes[:'zid_client_secret']
      end

      if attributes.key?(:'zid_access_token')
        self.zid_access_token = attributes[:'zid_access_token']
      end

      if attributes.key?(:'zid_authorization')
        self.zid_authorization = attributes[:'zid_authorization']
      end

      if attributes.key?(:'zid_refresh_token')
        self.zid_refresh_token = attributes[:'zid_refresh_token']
      end

      if attributes.key?(:'flipkart_client_id')
        self.flipkart_client_id = attributes[:'flipkart_client_id']
      end

      if attributes.key?(:'flipkart_client_secret')
        self.flipkart_client_secret = attributes[:'flipkart_client_secret']
      end

      if attributes.key?(:'allegro_client_id')
        self.allegro_client_id = attributes[:'allegro_client_id']
      end

      if attributes.key?(:'allegro_client_secret')
        self.allegro_client_secret = attributes[:'allegro_client_secret']
      end

      if attributes.key?(:'allegro_access_token')
        self.allegro_access_token = attributes[:'allegro_access_token']
      end

      if attributes.key?(:'allegro_refresh_token')
        self.allegro_refresh_token = attributes[:'allegro_refresh_token']
      end

      if attributes.key?(:'allegro_environment')
        self.allegro_environment = attributes[:'allegro_environment']
      else
        self.allegro_environment = 'production'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @cart_id.nil?
        invalid_properties.push('invalid value for "cart_id", cart_id cannot be nil.')
      end

      if @store_id.nil?
        invalid_properties.push('invalid value for "store_id", store_id cannot be nil.')
      end

      if !@hybris_websites.nil? && @hybris_websites.length < 1
        invalid_properties.push('invalid value for "hybris_websites", number of items must be greater than or equal to 1.')
      end

      if @wix_app_id.nil?
        invalid_properties.push('invalid value for "wix_app_id", wix_app_id cannot be nil.')
      end

      if @wix_app_secret_key.nil?
        invalid_properties.push('invalid value for "wix_app_secret_key", wix_app_secret_key cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @cart_id.nil?
      cart_id_validator = EnumAttributeValidator.new('String', ["3DCart", "3DCartApi", "AceShop", "AmazonSP", "AspDotNetStorefront", "BigCartel", "BigcommerceApi", "Bol", "CommerceHQ", "Creloaded", "Cscart", "Cubecart", "Demandware", "EBay", "Ecwid", "EtsyAPIv3", "Flipkart", "Gambio", "Hybris", "JooCart", "Lazada", "LightSpeed", "Magento1212", "Magento2Api", "MercadoLibre", "MijoShop", "Miva", "Neto", "Opencart14", "Oscmax2", "Oscommerce22ms2", "Otto", "Oxid", "Pinnacle", "Prestashop", "PrestashopApi", "SSPremium", "Salla", "Shopify", "Shopee", "Shoplazza", "Shopline", "Shopware", "ShopwareApi", "Square", "Squarespace", "Temu", "Tiendanube", "TikTokShop", "Tomatocart", "Ubercart", "Virtuemart", "Volusion", "WPecommerce", "Walmart", "WebAsyst", "Wix", "Woocommerce", "WoocommerceApi", "Xcart", "Xtcommerce", "XtcommerceVeyton", "Zencart137", "Zid", "Zoey", "Zoho"])
      return false unless cart_id_validator.valid?(@cart_id)
      return false if @store_id.nil?
      return false if !@hybris_websites.nil? && @hybris_websites.length < 1
      return false if @wix_app_id.nil?
      return false if @wix_app_secret_key.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cart_id Object to be assigned
    def cart_id=(cart_id)
      validator = EnumAttributeValidator.new('String', ["3DCart", "3DCartApi", "AceShop", "AmazonSP", "AspDotNetStorefront", "BigCartel", "BigcommerceApi", "Bol", "CommerceHQ", "Creloaded", "Cscart", "Cubecart", "Demandware", "EBay", "Ecwid", "EtsyAPIv3", "Flipkart", "Gambio", "Hybris", "JooCart", "Lazada", "LightSpeed", "Magento1212", "Magento2Api", "MercadoLibre", "MijoShop", "Miva", "Neto", "Opencart14", "Oscmax2", "Oscommerce22ms2", "Otto", "Oxid", "Pinnacle", "Prestashop", "PrestashopApi", "SSPremium", "Salla", "Shopify", "Shopee", "Shoplazza", "Shopline", "Shopware", "ShopwareApi", "Square", "Squarespace", "Temu", "Tiendanube", "TikTokShop", "Tomatocart", "Ubercart", "Virtuemart", "Volusion", "WPecommerce", "Walmart", "WebAsyst", "Wix", "Woocommerce", "WoocommerceApi", "Xcart", "Xtcommerce", "XtcommerceVeyton", "Zencart137", "Zid", "Zoey", "Zoho"])
      unless validator.valid?(cart_id)
        fail ArgumentError, "invalid value for \"cart_id\", must be one of #{validator.allowable_values}."
      end
      @cart_id = cart_id
    end

    # Custom attribute writer method with validation
    # @param [Object] hybris_websites Value to be assigned
    def hybris_websites=(hybris_websites)
      if hybris_websites.nil?
        fail ArgumentError, 'hybris_websites cannot be nil'
      end

      if hybris_websites.length < 1
        fail ArgumentError, 'invalid value for "hybris_websites", number of items must be greater than or equal to 1.'
      end

      @hybris_websites = hybris_websites
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cart_id == o.cart_id &&
          store_url == o.store_url &&
          bridge_url == o.bridge_url &&
          store_root == o.store_root &&
          store_key == o.store_key &&
          shared_secret == o.shared_secret &&
          validate_version == o.validate_version &&
          verify == o.verify &&
          db_tables_prefix == o.db_tables_prefix &&
          user_agent == o.user_agent &&
          ftp_host == o.ftp_host &&
          ftp_user == o.ftp_user &&
          ftp_password == o.ftp_password &&
          ftp_port == o.ftp_port &&
          ftp_store_dir == o.ftp_store_dir &&
          api_key_3dcart == o.api_key_3dcart &&
          admin_account == o.admin_account &&
          api_path == o.api_path &&
          api_key_bigcommerce == o.api_key_bigcommerce &&
          client_id == o.client_id &&
          access_token == o.access_token &&
          context == o.context &&
          access_token == o.access_token &&
          api_key_shopify == o.api_key_shopify &&
          api_password == o.api_password &&
          access_token_shopify == o.access_token_shopify &&
          api_key == o.api_key &&
          api_username == o.api_username &&
          encrypted_password == o.encrypted_password &&
          login == o.login &&
          api_user_adnsf == o.api_user_adnsf &&
          api_pass == o.api_pass &&
          private_key == o.private_key &&
          app_token == o.app_token &&
          etsy_keystring == o.etsy_keystring &&
          etsy_shared_secret == o.etsy_shared_secret &&
          token_secret == o.token_secret &&
          etsy_client_id == o.etsy_client_id &&
          etsy_refresh_token == o.etsy_refresh_token &&
          ebay_client_id == o.ebay_client_id &&
          ebay_client_secret == o.ebay_client_secret &&
          ebay_runame == o.ebay_runame &&
          ebay_access_token == o.ebay_access_token &&
          ebay_refresh_token == o.ebay_refresh_token &&
          ebay_environment == o.ebay_environment &&
          ebay_site_id == o.ebay_site_id &&
          dw_client_id == o.dw_client_id &&
          dw_api_pass == o.dw_api_pass &&
          demandware_user_name == o.demandware_user_name &&
          demandware_user_password == o.demandware_user_password &&
          store_id == o.store_id &&
          seller_id == o.seller_id &&
          environment == o.environment &&
          hybris_client_id == o.hybris_client_id &&
          hybris_client_secret == o.hybris_client_secret &&
          hybris_username == o.hybris_username &&
          hybris_password == o.hybris_password &&
          hybris_websites == o.hybris_websites &&
          walmart_client_id == o.walmart_client_id &&
          walmart_client_secret == o.walmart_client_secret &&
          walmart_environment == o.walmart_environment &&
          walmart_channel_type == o.walmart_channel_type &&
          walmart_region == o.walmart_region &&
          lightspeed_api_key == o.lightspeed_api_key &&
          lightspeed_api_secret == o.lightspeed_api_secret &&
          shoplazza_access_token == o.shoplazza_access_token &&
          shoplazza_shared_secret == o.shoplazza_shared_secret &&
          shopware_access_key == o.shopware_access_key &&
          shopware_api_key == o.shopware_api_key &&
          shopware_api_secret == o.shopware_api_secret &&
          commercehq_api_key == o.commercehq_api_key &&
          commercehq_api_password == o.commercehq_api_password &&
          _3dcart_private_key == o._3dcart_private_key &&
          _3dcart_access_token == o._3dcart_access_token &&
          wc_consumer_key == o.wc_consumer_key &&
          wc_consumer_secret == o.wc_consumer_secret &&
          magento_consumer_key == o.magento_consumer_key &&
          magento_consumer_secret == o.magento_consumer_secret &&
          magento_access_token == o.magento_access_token &&
          magento_token_secret == o.magento_token_secret &&
          prestashop_webservice_key == o.prestashop_webservice_key &&
          wix_app_id == o.wix_app_id &&
          wix_app_secret_key == o.wix_app_secret_key &&
          wix_instance_id == o.wix_instance_id &&
          wix_refresh_token == o.wix_refresh_token &&
          mercado_libre_app_id == o.mercado_libre_app_id &&
          mercado_libre_app_secret_key == o.mercado_libre_app_secret_key &&
          mercado_libre_refresh_token == o.mercado_libre_refresh_token &&
          zid_client_id == o.zid_client_id &&
          zid_client_secret == o.zid_client_secret &&
          zid_access_token == o.zid_access_token &&
          zid_authorization == o.zid_authorization &&
          zid_refresh_token == o.zid_refresh_token &&
          flipkart_client_id == o.flipkart_client_id &&
          flipkart_client_secret == o.flipkart_client_secret &&
          allegro_client_id == o.allegro_client_id &&
          allegro_client_secret == o.allegro_client_secret &&
          allegro_access_token == o.allegro_access_token &&
          allegro_refresh_token == o.allegro_refresh_token &&
          allegro_environment == o.allegro_environment
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cart_id, store_url, bridge_url, store_root, store_key, shared_secret, validate_version, verify, db_tables_prefix, user_agent, ftp_host, ftp_user, ftp_password, ftp_port, ftp_store_dir, api_key_3dcart, admin_account, api_path, api_key_bigcommerce, client_id, access_token, context, access_token, api_key_shopify, api_password, access_token_shopify, api_key, api_username, encrypted_password, login, api_user_adnsf, api_pass, private_key, app_token, etsy_keystring, etsy_shared_secret, token_secret, etsy_client_id, etsy_refresh_token, ebay_client_id, ebay_client_secret, ebay_runame, ebay_access_token, ebay_refresh_token, ebay_environment, ebay_site_id, dw_client_id, dw_api_pass, demandware_user_name, demandware_user_password, store_id, seller_id, environment, hybris_client_id, hybris_client_secret, hybris_username, hybris_password, hybris_websites, walmart_client_id, walmart_client_secret, walmart_environment, walmart_channel_type, walmart_region, lightspeed_api_key, lightspeed_api_secret, shoplazza_access_token, shoplazza_shared_secret, shopware_access_key, shopware_api_key, shopware_api_secret, commercehq_api_key, commercehq_api_password, _3dcart_private_key, _3dcart_access_token, wc_consumer_key, wc_consumer_secret, magento_consumer_key, magento_consumer_secret, magento_access_token, magento_token_secret, prestashop_webservice_key, wix_app_id, wix_app_secret_key, wix_instance_id, wix_refresh_token, mercado_libre_app_id, mercado_libre_app_secret_key, mercado_libre_refresh_token, zid_client_id, zid_client_secret, zid_access_token, zid_authorization, zid_refresh_token, flipkart_client_id, flipkart_client_secret, allegro_client_id, allegro_client_secret, allegro_access_token, allegro_refresh_token, allegro_environment].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
