=begin
#API2Cart OpenAPI

#API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module OpenapiClient
  class OrderPreestimateShippingList
    # This parameter is used for selecting a warehouse where you need to set/modify a product quantity.
    attr_accessor :warehouse_id

    # Retrieves orders specified by customer id
    attr_accessor :customer_id

    # Retrieves orders specified by customer email
    attr_accessor :customer_email

    # Store Id
    attr_accessor :store_id

    # Specifies first shipping address
    attr_accessor :shipp_address_1

    # Specifies shipping city
    attr_accessor :shipp_city

    # Specifies shipping postcode
    attr_accessor :shipp_postcode

    # Specifies shipping state code
    attr_accessor :shipp_state

    # Specifies shipping country code
    attr_accessor :shipp_country

    # Set this parameter in order to choose which entity fields you want to retrieve
    attr_accessor :params

    # Set this parameter in order to choose which entity fields you want to ignore. Works only if parameter `params` equal force_all
    attr_accessor :exclude

    attr_accessor :order_item

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'warehouse_id' => :'warehouse_id',
        :'customer_id' => :'customer_id',
        :'customer_email' => :'customer_email',
        :'store_id' => :'store_id',
        :'shipp_address_1' => :'shipp_address_1',
        :'shipp_city' => :'shipp_city',
        :'shipp_postcode' => :'shipp_postcode',
        :'shipp_state' => :'shipp_state',
        :'shipp_country' => :'shipp_country',
        :'params' => :'params',
        :'exclude' => :'exclude',
        :'order_item' => :'order_item'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'warehouse_id' => :'String',
        :'customer_id' => :'String',
        :'customer_email' => :'String',
        :'store_id' => :'String',
        :'shipp_address_1' => :'String',
        :'shipp_city' => :'String',
        :'shipp_postcode' => :'String',
        :'shipp_state' => :'String',
        :'shipp_country' => :'String',
        :'params' => :'String',
        :'exclude' => :'String',
        :'order_item' => :'Array<OrderPreestimateShippingListOrderItemInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::OrderPreestimateShippingList` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::OrderPreestimateShippingList`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'warehouse_id')
        self.warehouse_id = attributes[:'warehouse_id']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'store_id')
        self.store_id = attributes[:'store_id']
      end

      if attributes.key?(:'shipp_address_1')
        self.shipp_address_1 = attributes[:'shipp_address_1']
      end

      if attributes.key?(:'shipp_city')
        self.shipp_city = attributes[:'shipp_city']
      end

      if attributes.key?(:'shipp_postcode')
        self.shipp_postcode = attributes[:'shipp_postcode']
      end

      if attributes.key?(:'shipp_state')
        self.shipp_state = attributes[:'shipp_state']
      end

      if attributes.key?(:'shipp_country')
        self.shipp_country = attributes[:'shipp_country']
      else
        self.shipp_country = nil
      end

      if attributes.key?(:'params')
        self.params = attributes[:'params']
      else
        self.params = 'force_all'
      end

      if attributes.key?(:'exclude')
        self.exclude = attributes[:'exclude']
      end

      if attributes.key?(:'order_item')
        if (value = attributes[:'order_item']).is_a?(Array)
          self.order_item = value
        end
      else
        self.order_item = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @shipp_country.nil?
        invalid_properties.push('invalid value for "shipp_country", shipp_country cannot be nil.')
      end

      if @order_item.nil?
        invalid_properties.push('invalid value for "order_item", order_item cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @shipp_country.nil?
      return false if @order_item.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          warehouse_id == o.warehouse_id &&
          customer_id == o.customer_id &&
          customer_email == o.customer_email &&
          store_id == o.store_id &&
          shipp_address_1 == o.shipp_address_1 &&
          shipp_city == o.shipp_city &&
          shipp_postcode == o.shipp_postcode &&
          shipp_state == o.shipp_state &&
          shipp_country == o.shipp_country &&
          params == o.params &&
          exclude == o.exclude &&
          order_item == o.order_item
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [warehouse_id, customer_id, customer_email, store_id, shipp_address_1, shipp_city, shipp_postcode, shipp_state, shipp_country, params, exclude, order_item].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
