=begin
#API2Cart OpenAPI

#API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ProductVariantUpdateBatchPayloadInner
    attr_accessor :id

    attr_accessor :product_id

    attr_accessor :name

    attr_accessor :description

    attr_accessor :short_description

    attr_accessor :sku

    attr_accessor :upc

    attr_accessor :mpn

    attr_accessor :gtin

    attr_accessor :isbn

    attr_accessor :status

    attr_accessor :price

    attr_accessor :special_price

    attr_accessor :cost_price

    attr_accessor :retail_price

    # If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    attr_accessor :advanced_prices

    attr_accessor :quantity

    attr_accessor :reserve_quantity

    attr_accessor :increase_quantity

    attr_accessor :reduce_quantity

    attr_accessor :warehouse_id

    attr_accessor :manufacturer_id

    attr_accessor :weight

    attr_accessor :height

    attr_accessor :length

    attr_accessor :width

    attr_accessor :store_id

    attr_accessor :lang_id

    attr_accessor :tax_class_id

    attr_accessor :backorder_status

    attr_accessor :visible

    attr_accessor :is_default

    attr_accessor :in_stock

    attr_accessor :is_virtual

    attr_accessor :downloadable

    attr_accessor :manage_stock

    attr_accessor :is_free_shipping

    attr_accessor :seo_url

    attr_accessor :meta_title

    attr_accessor :meta_description

    attr_accessor :meta_keywords

    # If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    attr_accessor :categories_ids

    attr_accessor :stores_ids

    # The passed items will completely replace the original items
    attr_accessor :images

    attr_accessor :product_images_ids

    # If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    attr_accessor :related_products_ids

    # If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    attr_accessor :up_sell_products_ids

    # If an empty array is passed, all entries will be deleted when the 'nested_items_update_behaviour' parameter is set to 'replace'.
    attr_accessor :cross_sell_products_ids

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'product_id' => :'product_id',
        :'name' => :'name',
        :'description' => :'description',
        :'short_description' => :'short_description',
        :'sku' => :'sku',
        :'upc' => :'upc',
        :'mpn' => :'mpn',
        :'gtin' => :'gtin',
        :'isbn' => :'isbn',
        :'status' => :'status',
        :'price' => :'price',
        :'special_price' => :'special_price',
        :'cost_price' => :'cost_price',
        :'retail_price' => :'retail_price',
        :'advanced_prices' => :'advanced_prices',
        :'quantity' => :'quantity',
        :'reserve_quantity' => :'reserve_quantity',
        :'increase_quantity' => :'increase_quantity',
        :'reduce_quantity' => :'reduce_quantity',
        :'warehouse_id' => :'warehouse_id',
        :'manufacturer_id' => :'manufacturer_id',
        :'weight' => :'weight',
        :'height' => :'height',
        :'length' => :'length',
        :'width' => :'width',
        :'store_id' => :'store_id',
        :'lang_id' => :'lang_id',
        :'tax_class_id' => :'tax_class_id',
        :'backorder_status' => :'backorder_status',
        :'visible' => :'visible',
        :'is_default' => :'is_default',
        :'in_stock' => :'in_stock',
        :'is_virtual' => :'is_virtual',
        :'downloadable' => :'downloadable',
        :'manage_stock' => :'manage_stock',
        :'is_free_shipping' => :'is_free_shipping',
        :'seo_url' => :'seo_url',
        :'meta_title' => :'meta_title',
        :'meta_description' => :'meta_description',
        :'meta_keywords' => :'meta_keywords',
        :'categories_ids' => :'categories_ids',
        :'stores_ids' => :'stores_ids',
        :'images' => :'images',
        :'product_images_ids' => :'product_images_ids',
        :'related_products_ids' => :'related_products_ids',
        :'up_sell_products_ids' => :'up_sell_products_ids',
        :'cross_sell_products_ids' => :'cross_sell_products_ids'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'product_id' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'short_description' => :'String',
        :'sku' => :'String',
        :'upc' => :'String',
        :'mpn' => :'String',
        :'gtin' => :'String',
        :'isbn' => :'String',
        :'status' => :'String',
        :'price' => :'Float',
        :'special_price' => :'Float',
        :'cost_price' => :'Float',
        :'retail_price' => :'Float',
        :'advanced_prices' => :'Array<ProductUpdateBatchPayloadInnerAdvancedPricesInner>',
        :'quantity' => :'Float',
        :'reserve_quantity' => :'Float',
        :'increase_quantity' => :'Float',
        :'reduce_quantity' => :'Float',
        :'warehouse_id' => :'String',
        :'manufacturer_id' => :'String',
        :'weight' => :'Float',
        :'height' => :'Float',
        :'length' => :'Float',
        :'width' => :'Float',
        :'store_id' => :'String',
        :'lang_id' => :'String',
        :'tax_class_id' => :'String',
        :'backorder_status' => :'String',
        :'visible' => :'String',
        :'is_default' => :'Boolean',
        :'in_stock' => :'Boolean',
        :'is_virtual' => :'Boolean',
        :'downloadable' => :'Boolean',
        :'manage_stock' => :'Boolean',
        :'is_free_shipping' => :'Boolean',
        :'seo_url' => :'String',
        :'meta_title' => :'String',
        :'meta_description' => :'String',
        :'meta_keywords' => :'Array<String>',
        :'categories_ids' => :'Array<String>',
        :'stores_ids' => :'Array<String>',
        :'images' => :'Array<ProductAddBatchPayloadInnerImagesInner>',
        :'product_images_ids' => :'Array<String>',
        :'related_products_ids' => :'Array<String>',
        :'up_sell_products_ids' => :'Array<String>',
        :'cross_sell_products_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ProductVariantUpdateBatchPayloadInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ProductVariantUpdateBatchPayloadInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      else
        self.product_id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'short_description')
        self.short_description = attributes[:'short_description']
      end

      if attributes.key?(:'sku')
        self.sku = attributes[:'sku']
      end

      if attributes.key?(:'upc')
        self.upc = attributes[:'upc']
      end

      if attributes.key?(:'mpn')
        self.mpn = attributes[:'mpn']
      end

      if attributes.key?(:'gtin')
        self.gtin = attributes[:'gtin']
      end

      if attributes.key?(:'isbn')
        self.isbn = attributes[:'isbn']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      end

      if attributes.key?(:'special_price')
        self.special_price = attributes[:'special_price']
      end

      if attributes.key?(:'cost_price')
        self.cost_price = attributes[:'cost_price']
      end

      if attributes.key?(:'retail_price')
        self.retail_price = attributes[:'retail_price']
      end

      if attributes.key?(:'advanced_prices')
        if (value = attributes[:'advanced_prices']).is_a?(Array)
          self.advanced_prices = value
        end
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      end

      if attributes.key?(:'reserve_quantity')
        self.reserve_quantity = attributes[:'reserve_quantity']
      end

      if attributes.key?(:'increase_quantity')
        self.increase_quantity = attributes[:'increase_quantity']
      end

      if attributes.key?(:'reduce_quantity')
        self.reduce_quantity = attributes[:'reduce_quantity']
      end

      if attributes.key?(:'warehouse_id')
        self.warehouse_id = attributes[:'warehouse_id']
      end

      if attributes.key?(:'manufacturer_id')
        self.manufacturer_id = attributes[:'manufacturer_id']
      end

      if attributes.key?(:'weight')
        self.weight = attributes[:'weight']
      end

      if attributes.key?(:'height')
        self.height = attributes[:'height']
      end

      if attributes.key?(:'length')
        self.length = attributes[:'length']
      end

      if attributes.key?(:'width')
        self.width = attributes[:'width']
      end

      if attributes.key?(:'store_id')
        self.store_id = attributes[:'store_id']
      end

      if attributes.key?(:'lang_id')
        self.lang_id = attributes[:'lang_id']
      end

      if attributes.key?(:'tax_class_id')
        self.tax_class_id = attributes[:'tax_class_id']
      end

      if attributes.key?(:'backorder_status')
        self.backorder_status = attributes[:'backorder_status']
      end

      if attributes.key?(:'visible')
        self.visible = attributes[:'visible']
      end

      if attributes.key?(:'is_default')
        self.is_default = attributes[:'is_default']
      end

      if attributes.key?(:'in_stock')
        self.in_stock = attributes[:'in_stock']
      end

      if attributes.key?(:'is_virtual')
        self.is_virtual = attributes[:'is_virtual']
      end

      if attributes.key?(:'downloadable')
        self.downloadable = attributes[:'downloadable']
      end

      if attributes.key?(:'manage_stock')
        self.manage_stock = attributes[:'manage_stock']
      end

      if attributes.key?(:'is_free_shipping')
        self.is_free_shipping = attributes[:'is_free_shipping']
      end

      if attributes.key?(:'seo_url')
        self.seo_url = attributes[:'seo_url']
      end

      if attributes.key?(:'meta_title')
        self.meta_title = attributes[:'meta_title']
      end

      if attributes.key?(:'meta_description')
        self.meta_description = attributes[:'meta_description']
      end

      if attributes.key?(:'meta_keywords')
        if (value = attributes[:'meta_keywords']).is_a?(Array)
          self.meta_keywords = value
        end
      end

      if attributes.key?(:'categories_ids')
        if (value = attributes[:'categories_ids']).is_a?(Array)
          self.categories_ids = value
        end
      end

      if attributes.key?(:'stores_ids')
        if (value = attributes[:'stores_ids']).is_a?(Array)
          self.stores_ids = value
        end
      end

      if attributes.key?(:'images')
        if (value = attributes[:'images']).is_a?(Array)
          self.images = value
        end
      end

      if attributes.key?(:'product_images_ids')
        if (value = attributes[:'product_images_ids']).is_a?(Array)
          self.product_images_ids = value
        end
      end

      if attributes.key?(:'related_products_ids')
        if (value = attributes[:'related_products_ids']).is_a?(Array)
          self.related_products_ids = value
        end
      end

      if attributes.key?(:'up_sell_products_ids')
        if (value = attributes[:'up_sell_products_ids']).is_a?(Array)
          self.up_sell_products_ids = value
        end
      end

      if attributes.key?(:'cross_sell_products_ids')
        if (value = attributes[:'cross_sell_products_ids']).is_a?(Array)
          self.cross_sell_products_ids = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @product_id.nil?
        invalid_properties.push('invalid value for "product_id", product_id cannot be nil.')
      end

      if !@meta_keywords.nil? && @meta_keywords.length < 1
        invalid_properties.push('invalid value for "meta_keywords", number of items must be greater than or equal to 1.')
      end

      if !@stores_ids.nil? && @stores_ids.length < 1
        invalid_properties.push('invalid value for "stores_ids", number of items must be greater than or equal to 1.')
      end

      if !@images.nil? && @images.length < 1
        invalid_properties.push('invalid value for "images", number of items must be greater than or equal to 1.')
      end

      if !@product_images_ids.nil? && @product_images_ids.length < 1
        invalid_properties.push('invalid value for "product_images_ids", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @product_id.nil?
      return false if !@meta_keywords.nil? && @meta_keywords.length < 1
      return false if !@stores_ids.nil? && @stores_ids.length < 1
      return false if !@images.nil? && @images.length < 1
      return false if !@product_images_ids.nil? && @product_images_ids.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] meta_keywords Value to be assigned
    def meta_keywords=(meta_keywords)
      if meta_keywords.nil?
        fail ArgumentError, 'meta_keywords cannot be nil'
      end

      if meta_keywords.length < 1
        fail ArgumentError, 'invalid value for "meta_keywords", number of items must be greater than or equal to 1.'
      end

      @meta_keywords = meta_keywords
    end

    # Custom attribute writer method with validation
    # @param [Object] stores_ids Value to be assigned
    def stores_ids=(stores_ids)
      if stores_ids.nil?
        fail ArgumentError, 'stores_ids cannot be nil'
      end

      if stores_ids.length < 1
        fail ArgumentError, 'invalid value for "stores_ids", number of items must be greater than or equal to 1.'
      end

      @stores_ids = stores_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] images Value to be assigned
    def images=(images)
      if images.nil?
        fail ArgumentError, 'images cannot be nil'
      end

      if images.length < 1
        fail ArgumentError, 'invalid value for "images", number of items must be greater than or equal to 1.'
      end

      @images = images
    end

    # Custom attribute writer method with validation
    # @param [Object] product_images_ids Value to be assigned
    def product_images_ids=(product_images_ids)
      if product_images_ids.nil?
        fail ArgumentError, 'product_images_ids cannot be nil'
      end

      if product_images_ids.length < 1
        fail ArgumentError, 'invalid value for "product_images_ids", number of items must be greater than or equal to 1.'
      end

      @product_images_ids = product_images_ids
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          product_id == o.product_id &&
          name == o.name &&
          description == o.description &&
          short_description == o.short_description &&
          sku == o.sku &&
          upc == o.upc &&
          mpn == o.mpn &&
          gtin == o.gtin &&
          isbn == o.isbn &&
          status == o.status &&
          price == o.price &&
          special_price == o.special_price &&
          cost_price == o.cost_price &&
          retail_price == o.retail_price &&
          advanced_prices == o.advanced_prices &&
          quantity == o.quantity &&
          reserve_quantity == o.reserve_quantity &&
          increase_quantity == o.increase_quantity &&
          reduce_quantity == o.reduce_quantity &&
          warehouse_id == o.warehouse_id &&
          manufacturer_id == o.manufacturer_id &&
          weight == o.weight &&
          height == o.height &&
          length == o.length &&
          width == o.width &&
          store_id == o.store_id &&
          lang_id == o.lang_id &&
          tax_class_id == o.tax_class_id &&
          backorder_status == o.backorder_status &&
          visible == o.visible &&
          is_default == o.is_default &&
          in_stock == o.in_stock &&
          is_virtual == o.is_virtual &&
          downloadable == o.downloadable &&
          manage_stock == o.manage_stock &&
          is_free_shipping == o.is_free_shipping &&
          seo_url == o.seo_url &&
          meta_title == o.meta_title &&
          meta_description == o.meta_description &&
          meta_keywords == o.meta_keywords &&
          categories_ids == o.categories_ids &&
          stores_ids == o.stores_ids &&
          images == o.images &&
          product_images_ids == o.product_images_ids &&
          related_products_ids == o.related_products_ids &&
          up_sell_products_ids == o.up_sell_products_ids &&
          cross_sell_products_ids == o.cross_sell_products_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, product_id, name, description, short_description, sku, upc, mpn, gtin, isbn, status, price, special_price, cost_price, retail_price, advanced_prices, quantity, reserve_quantity, increase_quantity, reduce_quantity, warehouse_id, manufacturer_id, weight, height, length, width, store_id, lang_id, tax_class_id, backorder_status, visible, is_default, in_stock, is_virtual, downloadable, manage_stock, is_free_shipping, seo_url, meta_title, meta_description, meta_keywords, categories_ids, stores_ids, images, product_images_ids, related_products_ids, up_sell_products_ids, cross_sell_products_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
