=begin
#API2Cart OpenAPI

#API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ProductUpdateBatchPayloadInnerAdvancedPricesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ProductUpdateBatchPayloadInnerAdvancedPricesInner do
  let(:instance) { OpenapiClient::ProductUpdateBatchPayloadInnerAdvancedPricesInner.new }

  describe 'test an instance of ProductUpdateBatchPayloadInnerAdvancedPricesInner' do
    it 'should create an instance of ProductUpdateBatchPayloadInnerAdvancedPricesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ProductUpdateBatchPayloadInnerAdvancedPricesInner)
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "group_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "quantity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
