name: Update ruby-sdk SDK

on:
  # Запускатися раз на тиждень (у неділю о 00:00 за UTC)
  schedule:
    - cron: '0 0 * * 0'
  # Додатково, щоб мати можливість запустити вручну
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_ruby_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ruby.tgz
        run: |
          curl -L -o ruby.tgz https://app.api2cart.com/sdk/openapi/ruby.tgz

      # Розпаковуємо, видаляючи 1 рівень (папку ruby)
      - name: Extract ruby.tgz
        run: |
          tar -xzf ruby.tgz --strip-components=1

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update ruby SDK [skip ci]"
          git push
